name: Deploy Frontend Workflow

on:
  push:
    paths:
      - 'frontend_refactor/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: frontend_refactor

      - name: Build project
        run: npm run build
        working-directory: frontend_refactor

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "frontend_refactor/dist/*"
          target: "/home/ec2-user/bookhub-deploy-frontend/"

      - name: Deploy to Nginx directory
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo cp -r /home/ec2-user/bookhub-deploy-frontend/dist/* /usr/share/nginx/html/
            sudo systemctl restart nginx
